language: java
sudo: required
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
os:
- linux
install: true
script: mvn clean install
before_deploy:
- bash ./ci/before_deploy.sh
deploy:
  provider: script
  script: bash ./ci/deploy.sh
  on:
    branch: master
    tags: true
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email: laaws-dev@lists.lockss.org
env:
  global:
  - secure: xoMPoqtoEjEn/bqv2n/JhE1g9TnirJ8YyBFiI/JvrXCVXqrcXeqFQEWa+sfg6Oz3upFzPteJvtPo3m98al1gcZnA4OKRVIVcbf+8CHwt2IFOeFtZfZ67VJC18TVJEDa7nPejue2IEIVu4sYVc+FXmlJBzMlHCsoGAb0EdXMHdA3pGXSSpLvxcNKXO/yeH80Sfy6Lr1I1ZrCpRcbe+Dls2H72JrifpJ/IEI/lwxELnKEVY9lywbmXlmLQhmYokbcfmgISL0FWig3cwqbKekhH6ylyhNQS5VGVTG7B+YGN49eaVS8B/QytN2cUQHsdy1cIDZeBPCMQ0ppNzRGWvskB4v5ArAYhGtH3KR9138VaVF9Dm2vvvmF0ySdxUwxpfHXxJxq+r5ao3/oqBy3WEpIMu+hpq5VF5lQMeSG0aDUp8nFviuZciFfb7IES6q2cfcGtFFWKWavuSL5gSVRzXn11cAFnYrGaw2BsRVe5hh9u+V7BkPNQg9NOqDQ4f0OCSkilJBRMgZuiJVcG0hrbKWEPZlMhcoVs84mKxWe+uRnVM2COLalPKqS2Vcn+aUSNgwCsM6jAqNQEzUAh++EzKwX89qHW9xtRu1RetLEs+QChklzTAPcP19fS1enhJrNHX12zhIfd8pB9T463z9xweg7ZRkOp3SnpKJ+UqsG4ahsQnIQ=
  - secure: bvLBCoceWiUAYsQEdUvX6h6PtAUrGu+lVZc0182pS5EmoOVy6LuQvQqNpjFR0ztdDiY0XOLQFj9gfMrFjAWLVftq2Myy+ypAHkoGfnY75mtKSqiHvatRoVOkYPfSXhw1gjJOeQPvKz2GJS7HhxgMo6LTieOoWahxt8TL8Rpw2Ary1oZSvkOn3azCpfYzDW1LGHcX9JQSykaKlRuhVnEtz/bQvuUGN1o7ReQ4G1nDi4cO++M/XvsVciDzOAicQB8Na2Rbz/xUzfBykhRjWJxKRDHxzi65iXbGw3ov3M5IZzPFGN8BXqcd5ZpDTjmJAFCL82TRL5EK1pyh2tg/SDaYuLNN5K1nKvQvhZbviW0SRvtRMQPtc6tjUNbJBUoqptdCgCLuIJ55jABu594R+tvw7A1HP4G+INo1bp/C0GtHxHIZh6K9W6vKjzYQr/H83+gIi2r1nPxSvvk0XKpTnnsIJJTE9Fcf54vV2B1x1oyQoNufWQAN2MRaTYIeOIiUyCA2nnwtpI7L18Ak8VHW19hTm4pXAe2DS15RNo+aLi4spInVWdu0cs/QilMSvMrATKZIPAeEWpgfV+2E8Nf0ALQ1Uf6VyPMorq36L6I6o+XjmmyCeCQENx07iYk2FLDoxbFIsBnHaY38wAuMdds937d1zVY3XiUijwMkMaFZTKhl5cQ=
  - secure: UTda5grBuB4cl0HtmnrnirtH9zb8eE11LwzGZP9ccMao5YQtly7tjn9nDQjsHpX3+oRXLDupRvea2Q9pI5W0buvQ+HpdT58cYk71Pt18ibEqcqQlyTLVjo3wbmGYFnM6Z12e81Dq1/+hIrvYGqm+kyEq6UxWQ0H0eyc2kBFCZOYCClvhI6GmzlZHBct4KrpOvyzcLhfsr4YEO7hFf09PKkEWjtGDiWfdLyBBlNgoweRWthuRQdBIQqsL144cNgOIZdgv4uXk46TJGWUD6lrpMBIZzog0aTOO+K3qsNXD7u8ONargmap43MPg4oX9D7+xV9vOjjy6emcuuvQLgK7m/SQRvCLymyM5ClCsFyBzkRyD4grbVR8g5YGTtJfuOl0gAOZs2aTrmQku7Djv4ivarxLHikOqF8uZ4g25SyuC/CLs00U7jhHWWBzAkassi1ML6e0mH3kqt9jdvnWeL1ul3UIKAlHKKf2ehh/vuYFv931tcrA0gahswam94ouXaoBK5Tr38k1g4MuwVW9zS/7GzGqMV4mO/VwclRz1jjH6YQAV539h5Q8i206AgZTN9OBmGjUZbSb0aBVkcVCN9Hdrk0Wws86y8lOZbz02EGXsbNWgEwenk0p+ijqTL7qY9hb8bFR7zfMgMDl47x3FofOdKBRHbfNDD8XS5/xrjjtZcHs=
  - secure: xeG/AEQFxslNQhfYo0yqz5LLBspxdMu4U/s7vBBYDEa/DixMsLiwcqemIyEi9qs+hkOyZJ/StxQV2itJjbCIvmxUWg8zv5ldpq8GqMs9RQ5gISlnP8ldRxARsa6Yz8G2Scb6XrBPFucN7B08MjnzcAw/M17cMjpm0X4Sruh3cDQh7P2ZtLjGuBpyIctjL1pGAeLcZSSzZlM+z6BoJQp7PPFNWmKpEGzIxHe3osVVyQRO0GDeR7nklWy9vl/RiwO6kiYwvee3tcP6B3JpdRVVpiVNaGe2Shfp951a55QYSiTr2BD8UFMUbgmQ2wlwV9XEtIPiI/J0N+LSyJMd9n06ZCiMa2cB4FOkph7kaupWwow37aiVJTthzXscD3YKJ0c//qnxSszH2SDPrhymmuw7D0JIRgCQl9G98C76mRXOaaj1QC7jetxcUdRIDrQtxwkmJ8Agh7Te5deSWFDYQ4yMyoJNFjTXLRhVfmA+r3isGu3x5hoPtS222dPS42B982c6AorLWcpYCLEllZTkgAXXQ8rTLOwzGMVkISV4nrYs3SNg+XypAVmGMscQAieMxKrnIs8eUB3vWejqsZaWmFgVlTuvQ6vMFj/jzgLWWl3VlA1kMe+T8UyQ6GQH0MKD33NE+yHrxNBsRZHThh8kSLE2kYbYEp2yRGkck1UpOVyyXEg=
